# -*- mode: ruby -*-
# vi: set ft=ruby :

# If resizing of the disc becomes needed
# https://tuhrig.de/resizing-vagrant-box-disk-space/

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/bionic64"
  config.vm.box_check_update = true
  config.vm.network "private_network", ip: "192.168.10.100"
  config.vm.synced_folder "../", "/project", disabled: true
  config.vm.synced_folder ".", "/vagrant", disabled: true
  config.vm.hostname = "jakartaee-microprofile-box"
  config.vm.provider "virtualbox" do |vb|
    vb.gui = false
    vb.memory = "4096"
    vb.name = "docker-box"
    vb.cpus = 1
    vb.customize ["modifyvm", :id, "--vram", "20"]
    vb.customize ["modifyvm", :id, "--cpuexecutioncap", "80"]
    vb.customize ["modifyvm", :id, "--ioapic", "on"]
    vb.customize ["modifyvm", :id, "--uartmode1", "disconnected" ]
  end
  # Copy your own ssh config to your
  config.vm.provision "file", source: "ssh/config", destination: "/home/vagrant/.ssh/config"
  config.vm.provision "file", source: "ssh/id_rsa", destination: "/home/vagrant/.ssh/id_rsa"
  config.vm.provision "file", source: "ssh/id_rsa.pub", destination: "/home/vagrant/.ssh/id_rsa.pub"
  config.vm.provision :shell do |s|
    ssh_pub_key = File.readlines("ssh/id_rsa.pub").first.strip
    s.inline = <<-SHELL
        mkdir -p /root/.ssh
        echo #{ssh_pub_key} >> /home/vagrant/.ssh/authorized_keys
        echo #{ssh_pub_key} >> /root/.ssh/authorized_keys
        echo "export PATH=~/bin:$PATH" >>/home/vagrant/.profile
        echo "alias dps='docker ps'" >>/home/vagrant/.profile
        echo "alias dpsa='docker ps -a'" >>/home/vagrant/.profile
        echo "alias drmf='docker rm -f'" >>/home/vagrant/.profile
        echo "alias di='docker images'" >>/home/vagrant/.profile
        echo "alias dc='docker-compose'" >>/home/vagrant/.profile
        echo "alias dcu='docker-compose up'" >>/home/vagrant/.profile
        echo "alias dcdv='docker-compose down -v'" >>/home/vagrant/.profile
        # echo "alias kubectl='microk8s.kubectl'" >>/home/vagrant/.profile
        # echo "alias istioctl='microk8s.istioctl'" >>/home/vagrant/.profile
        chmod 600 /home/vagrant/.ssh/*
    SHELL
  end
  config.vm.provision "shell", path: "setup/install.sh"
end
